services:
  db:
    image: postgres:16.0-alpine
    container_name: kwishes_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=kwishes
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      dockerfile: API.Dockerfile
    image: kwishes-api:latest
    container_name: kwishes_api
    volumes:
      - /kwishes-deploy/configs/API:/kwishes/configs
      - /kwishes-deploy/static:/kwishes/static
    networks:
      - internal
    ports:
      - "80:8080"


volumes:
  db_data:
    
networks:
  internal: