services:
  db:
    image: postgres:16.0-alpine
    container_name: kwishes_db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kwishes
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./init-local-data.sql:/docker-entrypoint-initdb.d/2-init-data.sql
    networks:
      - internal
    ports:
      - "5432:5432"
        
volumes:
  db_data:

networks:
  internal: